### ISSUE TITLE
consider adding Ubiq miner maybe?

### ISSUE THREAD

**Issue by kusayuzayushko** [greerso/smOS-unsupported-miners#9]
link to the builds https://github.com/ubiq/ubqminer/releases

**Comment by greerso** [comment]
done, but couldn't do it with the main script you can use this command.  
```
sudo bash -c "$(curl https://raw.githubusercontent.com/greerso/smOS-unsupported-miners/master/addons/Ubqminer_ethminer-0.11.0.sh)"
```

**Comment by jyap808** [comment]
@greerso thanks for adding support to Ubqminer. @kusayuzayushko thanks for the request

so here are the 2 blog posts which outline Ubqhash. one is an intro post and one is announcing the hard fork
https://blog.ubiqsmart.com/introducing-ubqhash-8fa515befd7

This article outlines the journey taken towards creating a new independent Proof-of-Work algorithm for Ubiq which we have called Ubqhash.
https://blog.ubiqsmart.com/announcing-the-uip-1-hard-fork-84d9b8b3b924

you'll be happy to know the motivation for Ubqhash is to eliminate the threat of NiceHash style attacks on ethash chains

**Comment by schmickter** [comment]
this worked great for me! thanks for taking all the hard work out of it

**Comment by poordutchguy** [comment]
Awesome !
Thanks for adding, I have always been running ethos, now I am setting up first test rig to smos and soon I hope to put my other 6 rigs on smos !
